name: sync-wiki
on:
  push:
      paths:
        # Trigger only when wiki directory changes
        - 'docs/**'
      branches:
        # And only on master branch
        - master
  repository_dispatch:
    types: [docs]
  gollum:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  GIT_AUTHOR_NAME: ${{ github.repository_owner }}
  GIT_AUTHER_EMAIL: ${{ github.actor }}
jobs:
  sync-docs-to-wiki:
    runs-on: ubuntu-latest
    if: github.event_name != 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Sync docs to Wiki
        uses: pablordoricaw/wiki-sync-action@master
        with:
          source: docs
          destination: wiki
          token: ${{ secrets.WIKI_SYNC_PAT_TOKEN }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}"
  
  sync-wiki-to-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WIKI_SYNC_PAT_TOKEN }} # allows us to push back to repo
          ref: master
      - name: Sync Wiki to docs
        uses: pablordoricaw/wiki-sync-action@master
        with:
          source: wiki
          destination: docs
          token: ${{ secrets.WIKI_SYNC_PAT_TOKEN }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}"
          branch: master
